name: jurix-mlfow

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8.1
  - pip
  - pip:
    - jupyter
    - nltk
    - mlflow
    - scikit-learn
    - pandas
    - scipy
    - spacy
